version: 2.1

orbs:
  php: circleci/php@1.1.0

workflows:
  version: 2
  test_and_check:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/php:8.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            sudo mv composer.phar /usr/local/bin/composer

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run:
          name: Install Composer dependencies
          command: |
            composer install --no-interaction --prefer-dist --optimize-autoloader

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run:
          name: Run tests
          command: |
            mkdir -p build
            ./vendor/bin/pest

      - run:
          name: Run PHPStan static analysis
          command: |
            mkdir -p build
            ./vendor/bin/phpstan analyse

      - run:
          name: Check code style with Pint
          command: |
            mkdir -p build
            ./vendor/bin/pint --test
